### ISSUE TITLE
Wget install instruction does not work (on UDM with firmware 1.11-023)

### ISSUE THREAD

**Issue by StreborStrebor** [bruvv/kpn_ipv6_udm-pro#1]
Thanks for this!

WGET gives an error (on my UDM with FW 1.11.0-23)
This line does work:

curl -L https://raw.githubusercontent.com/bruvv/kpn_ipv6_udm-pro/main/10-fix_ipv6.sh -o 10-fix_ipv6.sh

**Comment by bruvv** [comment]
Good one! Fixed it.
